# Generated by Django 3.2.3 on 2021-05-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardgame.player', verbose_name='Winner'),
        ),
    ]
