# Generated by Django 3.2.3 on 2021-05-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_alter_statistic_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.CharField(default=[], max_length=80)),
                ('board', models.CharField(default=[], max_length=250)),
                ('card', models.CharField(default='', max_length=3)),
                ('game_participants', models.CharField(default=[], max_length=250)),
                ('who_turn', models.PositiveIntegerField(default=0)),
                ('game_status', models.BooleanField(default=False)),
                ('is_draw', models.BooleanField(default=False)),
                ('turn_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
